import streamlit as st
import numpy as np
import matplotlib.pyplot as plt

st.title("Welcome to... whatever the heck of a project this is.")
st.subheader("This is the result of many contributions from various computer scientists and mathematicians around the world, " +
        "Gathering information from every possible source and placing them in this abomination of a machine that displays random " + 
        "three-dimensional objects and completely random lines and colors. WHAT A COMPLETE WASTE OF TIME. " + 
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla gravida magna sed velit commodo auctor. Fusce sit amet vestibulum lorem. Nullam interdum ligula aliquam ex euismod facilisis. Curabitur pulvinar sapien enim, id finibus justo accumsan vel. Sed rutrum maximus orci, eu ultrices mauris efficitur nec. Sed vel ultrices eros, nec aliquam velit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent ornare est a odio mollis semper. Nulla porttitor et urna ac molestie." +
        "Etiam consectetur quam neque, vitae auctor est tincidunt ac. Nullam elit velit, dapibus sit amet ultricies eu, cursus sit amet libero. Nam eu lorem consequat augue mollis dapibus. Aliquam ligula lacus, scelerisque vitae risus sit amet, ornare laoreet felis. Aliquam lectus nibh, ullamcorper quis sapien a, vulputate convallis eros. Sed nulla eros, hendrerit vel lacinia vitae, sodales non orci. Ut felis ante, aliquam eget hendrerit non, rhoncus ut mauris. Nulla ut pulvinar mi. Curabitur nec laoreet lectus, et luctus arcu. Etiam tincidunt id metus non iaculis. Sed nibh purus, elementum vitae fringilla quis, ornare non ipsum. Proin sodales leo sed arcu venenatis, in feugiat dolor pellentesque." +
        "Morbi sagittis augue mi. Nam consequat ultrices mauris, eu placerat libero rhoncus in. Vestibulum nec nisl eget elit mollis fringilla. Vivamus ullamcorper vulputate ex vel hendrerit. Mauris in ornare magna, sit amet ullamcorper sem. Maecenas tempus felis vitae tellus sollicitudin venenatis. In mollis, ipsum a aliquam fermentum, turpis enim lacinia neque, a accumsan lorem nulla a dolor. " +
        "Duis ac dolor in enim accumsan sodales non eget dolor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam condimentum, ligula in tristique faucibus, velit odio mattis lorem, pellentesque hendrerit tellus dolor ut dolor. Curabitur fermentum metus et hendrerit suscipit. Ut id massa purus. Nam quis tellus dignissim, dignissim tellus ut, accumsan elit. Nunc consectetur, risus vulputate venenatis luctus, leo nunc luctus dui, ac tristique eros quam a ipsum. Etiam dignissim nibh diam. Donec non molestie felis. Donec lacinia velit ac ante consectetur, eu luctus sem tempus. Duis a tempor leo. " + 
        "Vestibulum finibus purus eget consectetur volutpat. Nulla cursus dictum leo. Pellentesque fermentum lectus at mi ornare, eu blandit leo sollicitudin. Ut tempus imperdiet egestas. Nam at lacus ipsum. Maecenas in elit id urna sollicitudin malesuada. Phasellus varius magna enim, a tristique lacus auctor nec. Maecenas porta purus mi, vitae efficitur mauris posuere eu.")
